- name: Creates petclinic directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/devops/petclinic
    - /home/devops/petclinic/logs

- name: Copy petclinic JAR to tomcat
  become: true
  copy:
    src: "{{ BUILD_PATH }}/target/spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar"
    dest: /home/devops/petclinic

- name: start petclinic 
  shell: cd /home/devops/petclinic; nohup sudo java -jar spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar  2>&1 &
