- name: Creates petclinic directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /var/petclinic
    - /var/petclinic/logs

- name: Copy petclinic JAR to tomcat
  become: true
  copy:
    src: "{{ BUILD_PATH }}/target/spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar"
    dest: /var/petclinic/

- name: start petclinic 
  shell: cd /var/petclinic/; nohup sudo java -jar spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar  2>&1 &
